apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeasy-cli-setup
  namespace: argocd
spec:
  destination:
    namespace: argocd
  project: default
  source:
    repoURL: https://github.com/kubeasy-dev/cli-setup.git
    targetRevision: feat/add-kubeasy-argocd-project
    path: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true