apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeasy-cli-setup
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: kubeasy
  source:
    repoURL: https://github.com/kubeasy-dev/cli-setup.git
    targetRevision: main
    path: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true