apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeasy-challenge-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: challenge-operator-system
  project: default
  source:
    repoURL: https://github.com/kubeasy-dev/cli-setup.git
    targetRevision: HEAD
    path: operator
    directory:
      include: operator.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true